version: '2'

services:
 crc:
  image: app-docker136.hex.tno.nl:443/pitch/crc:5.3.0.0L
  mac_address: 00:18:8B:0D:4F:0B
  networks:
  - training
 
 web:
  image: app-docker136.hex.tno.nl:443/pitch/web:2.1.1
  ports:
  - "30003:8080"
  networks:
  - training
  environment:
  - constraint:node==app-docker03.hex.tno.nl

 xclient:
  extends:
   file: base-service.yml
   service: base-simservice
  image: app-docker136.hex.tno.nl:443/msaas-nld/start:pi

networks:
 training:  
  driver: overlay
  ipam:
   config:
   - subnet: 10.11.0.0/24
     gateway: 10.11.0.1


