version: '2'

services:
 crc:
  image: app-docker136.hex.tno.nl:443/pitch/crc:5.3.0.0L
  mac_address: 00:18:8B:0D:4F:0B
  networks:
  - training
 
 web:
  image: app-docker136.hex.tno.nl:443/pitch/web:2.1.1
  ports:
  - "30003:8080"
  networks:
  - training
  environment:
  - constraint:node==app-docker03.hex.tno.nl
  
 vrf:
  extends:
   file: base-service.yml
   service: base-simservice
  image: app-docker136.hex.tno.nl:443/msaas-nld/vrf:pi
  mac_address: 8C:70:5A:0B:58:7E
  hostname: mak
  environment:
  - DISPLAY=xserver:0
  networks:
  - x11
  
 pacer:
  extends:
   file: base-service.yml
   service: base-simservice
  image: app-docker136.hex.tno.nl:443/msaas-nld/pacer:pi
  command: -f Pacer
  environment:
  - ADVERTISED_ADDRESS=app-docker03.hex.tno.nl:443
  - constraint:node==app-docker03.hex.tno.nl
  - MINSLEEP=0
  ports:
  - "30002:8080"

 kml:
  extends:
   file: base-service.yml
   service: base-simservice
  image: app-docker136.hex.tno.nl:443/msaas-nld/kmlserver:pi
  command: -f KMLServer -i http://app-docker03.hex.tno.nl:443 -c pitch-logicaltime.config
  environment:
  - constraint:node==app-docker03.hex.tno.nl
  ports:
  - "30001:8080"
 
 damsim:
  extends:
   file: base-service.yml
   service: base-simservice
  image: app-docker136.hex.tno.nl:443/msaas-nld/damageserver:pi
  command: -f DamageServer -c pitch-logicaltime.config

 sensor:
  extends:
   file: base-service.yml
   service: base-simservice
  image: app-docker136.hex.tno.nl:443/msaas-nld/sensorserver:pi
  command: -f SensorServer -timemanaged

 xclient:
  extends:
   file: base-service.yml
   service: base-simservice
  image: app-docker136.hex.tno.nl:443/msaas-nld/start:pi
  environment:
  - DISPLAY=xserver:0
  networks:
  - x11

networks:
 training:  
  driver: overlay
  ipam:
   config:
   - subnet: 10.12.0.0/24
     gateway: 10.12.0.1
 x11:
  external:
   name: xserver_x11
