version: '3'

services:
  sesdb:
    image: app-docker136.hex.tno.nl:443/msaas-ger/sesdatabase:gulf
    environment:
      - POSTGRES_PASSWORD=postgres
      - affinity:image==app-docker136.hex.tno.nl:443/msaas-ger/sesdatabase:gulf
    volumes:
      - sesdata:/var/lib/postgresql/data
    networks:
      - training
  
  ses:
    image: app-docker136.hex.tno.nl:443/msaas-ger/ses:gulf
    environment:
      - JAVA_OPTIONS=-Xmx2048m
      - affinity:image==app-docker136.hex.tno.nl:443/msaas-ger/ses:gulf
    depends_on:
      - sesdb
    networks:
      - training

  proxy:
    image: app-docker136.hex.tno.nl:443/library/proxy
    command: :ses:8080
    ports:
      - "8080:8080"
    environment:
      - constraint:node==app-docker05.hex.tno.nl
    networks:
      - training
      
volumes:
  sesdata:
    external: false

networks:
 training:
  external:
   name: gulfnetwork_training
