version: '3'

services:
  sesdb:
    image: app-docker136.hex.tno.nl:443/msaas-ger/sesdatabase:gulf
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - affinity:image==app-docker136.hex.tno.nl:443/msaas-ger/sesdatabase:gulf
    volumes:
      - sesdata:/var/lib/postgresql/data
    networks:
      - training
  
  ses:
    image: app-docker136.hex.tno.nl:443/msaas-ger/ses:gulf
#    ports:
#      - "8080:8080"
    environment:
      - JAVA_OPTIONS=-Xmx2048m
      - affinity:image==app-docker136.hex.tno.nl:443/msaas-ger/ses:gulf
    depends_on:
      - sesdb
    networks:
      - training

volumes:
  sesdata:
    external: false

networks:
 training:
  external:
   name: demo_training
