version: '2'

services:
 crc:
  image: app-docker136.hex.tno.nl:443/pitch/crc:5.3.2.1L
  mac_address: 00:18:8B:0D:4F:0B
  environment:
  - CRC_NICKNAME=XXX
  - CRC_BOOSTERADDRESS=booster:8688
  - DISPLAY=xserver:0
  
 booster:
  image: app-docker136.hex.tno.nl:443/viking18/booster:2.2.9L
  mac_address: 00:18:8B:0D:4F:2B
  environment:
  - BOOSTER_MYID=176
  - BOOSTER_MYNAME=TNO
  
 vtg:
  image: app-docker136.hex.tno.nl:443/viking18/vrfvtg
  mac_address: 8C:70:5A:0B:58:7E
  hostname: mak
  environment:
  - PITCH_CRCADDRESS=XXX@booster:8688
  - DISPLAY=xserver:0

 nmea:
  image: app-docker136.hex.tno.nl:443/viking18/nmea
  environment:
  - PITCH_CRCADDRESS=XXX@booster:8688
  ports:
  - "443:9001"
  
 xserver:
  image: app-docker136.hex.tno.nl:443/library/xserver
  ports:
  - "8080:8080"
  environment:
  - DISPLAY_WIDTH=1920
  - DISPLAY_HEIGHT=1080
  
 kml:
  image: app-docker136.hex.tno.nl:443/msaas-nld/kmlserver:pi
  command: -f KMLServer
  environment:
  - PITCH_CRCADDRESS=XXX@booster:8688

 ge:
  image: app-docker136.hex.tno.nl:443/library/ge
  command: -f -r 10 Baltic http://kml:8080/kmlserver/entities 
  environment:
  - DISPLAY=xserver:0
