version: '2'

# Docker compose file where all components run on a single host

services:

# EPIC components
 diswebgw:
  image: app-docker136.hex.tno.nl:443/msaas-usa/dis-web-gw:epic
  ports:
  - "8282:8282"

 epic:
  image: app-docker136.hex.tno.nl:443/epic/epic:cax
  ports:
  - "7070:7070"
  environment:
  - dis_gw_url=app-docker01.hex.tno.nl

# HLA components
 crc:
  image: app-docker136.hex.tno.nl:443/pitch/crc:5.3.0.0L
  mac_address: 00:18:8B:0D:4F:0B
  environment:
  - DISPLAY=xserver:0

 dis:
  image: app-docker136.hex.tno.nl:443/pitch/dis:2.6.0L
  command: -auto
  mac_address: 00:18:8B:0D:4F:1B
  environment:
  - DISPLAY=xserver:0
  
 shipsim:
  image: app-docker136.hex.tno.nl:443/msaas-aus/shipsim:pi
  command: --fom-modules-dir allrofoms --scalable

 kml:
  image: app-docker136.hex.tno.nl:443/msaas-nld/kmlserver:pi
  command: -f KMLServer -iconurl http://kml:8080/kmlserver -d rofoms

 vrf:
  image: app-docker136.hex.tno.nl:443/msaas-nld/vrf:pi
  mac_address: 8C:70:5A:0B:58:7E
  hostname: mak
  command: -s demo -r
  environment:
  - DISPLAY=xserver:0

# General components
 ge:
  image: app-docker136.hex.tno.nl:443/library/ge
  command: -f -r 10 Gulf http://kml:8080/kmlserver/entities
  environment:
  - DISPLAY=xserver:0

 xserver:
  image: app-docker136.hex.tno.nl:443/library/xserver
  ports:
  - "8082:8080"
