version: '2'

services:
 placeholder:
  image: busybox
  networks:
  - training
  - disnet

networks:
 training:
  driver: overlay
  ipam:
   config:
   - subnet: 10.12.0.0/24
     gateway: 10.12.0.1
 disnet:
  driver: bridge
